### PR TITLE
Import toolchain Dockerfile

### PR DESCRIPTION
**Pull request by aleclearmind**
As promised, the Dockerfile to build a minimal toolchain.

```
make docker-image-debian-hexagon-cross ENGINE=podman
```

Let me know if it works.

### CODE REVIEW

**Comment by androm3da** [comment]
I'll give it a try.

**Comment by androm3da** [comment]
Locally, podman's not configured to pull images from dockerhub.  So I couldn't do it that way.  But I was able to use `ENGINE=docker` instead.  Using docker, the COPY command fails because AFAICT it searches relative to the working directory that the build is invoked from.  It looks like docker.py creates a temp dir to run the build from.  

I can't see an obvious way to find the build-hexagon-tools.sh script short of hardcoding an absolute path.  But even if I use an absolute path, docker appears to treat it as a path relative to the working dir.

https://docs.docker.com/engine/reference/builder/#copy doesn't seem to indicate a way to make the path relative to the `Dockerfile`.  Is this a difference in behavior between podman and docker?  I kinda thought it was supposed to be drop-in.

**Comment by aleclearmind** [comment]
In order to have `podman` fetch stuff from dockerhub I've the following in `/etc/containers/registries.conf`:

```
[registries.search]
registries = ['docker.io']
```

The `docker.py` script has an `--extra-files` option with files getting copied to the temporary build directory. I'm now augmenting it automatically with `debian-hexagon-cross.*` (where `debian-hexagon-cross` is the name of the image).
See the latest version of the commit.

I didn't test docker since I assumed they were fully compatible too.

**Comment by androm3da** [comment]
@aleclearmind this change LGTM, I can go ahead and merge it?

**Comment by aleclearmind** [comment]
I'm investigating some issues related to running the tests. I'll give you an update about this soon.

**Comment by aleclearmind** [comment]
I've pushed some changes. Now, configuring with `--enable-containers`, `make make check-tcg` tries to build inside the container and it's partially successful.

However I get the following errors:

```
qemu/tests/tcg/hexagon/exec_counters.c:50:52: error: unknown register name 'v0' in asm
               : : "r0", "r1", "r2", "sa0", "lc0", "v0", "p0");
                                                   ^
1 error generated.
```

I get similar errors with the following registers too: `cs0`, `cs1`.

Also:

```
qemu/tests/tcg/hexagon/scatter_gather.c:26:10: fatal error: 'hexagon_types.h' file not found
#include <hexagon_types.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

Is this something expected or am I doing something wrong?

**Comment by androm3da** [comment]
> Is this something expected or am I doing something wrong?

This is expected.  The latest content on quic/musl and quic/qemu now has the tests which can't build using the open source toolchain disabled for now.

**Comment by aleclearmind** [comment]
Uhm, is this for all the tests or only a portion? Can we have `master` have test that can be run publicly and then maybe have another branch for the SDK-only ones?

**Comment by androm3da** [comment]
> Uhm, is this for all the tests or only a portion? Can we have `master` have test that can be run publicly and then maybe have another branch for the SDK-only ones?

Only a portion.  The recent commits to quic/musl quic/qemu are to do just that.

Note that the linux target is not supported by the SDK, this was an artifact of having built some tests against a downstream linux toolchain.  Now `quic/qemu` is free of that dependency.  We will add commits to clang in order to enable these test cases, but for now those ones are disabled.

**Comment by androm3da** [comment]
> The recent commits to quic/musl quic/qemu are to do just that.

well I suppose we could just remove them too.  Either works for me.  cc @taylorsimpson

**Comment by androm3da** [comment]
Details:

`circ.c`, `scatter_gather.c`, `exec_counters.c` are disabled by #41 

`circ.c` uses registers not yet included in clang, others probably leverage `hexagon_types.h`.

We have outstanding tasks queued to make clang support these tests.

**Comment by aleclearmind** [comment]
I bumped the repos and now everything seems to work, except for the fact that I have to increase the timeout for tests to pass to 60 seconds, otherwise `test-mmap` fails. My machine is quite fast, is that normal?

Apart from this, it looks good to me.

**Comment by androm3da** [comment]
> I bumped the repos and now everything seems to work, except for the fact that I have to increase the timeout for tests to pass to 60 seconds, otherwise `test-mmap` fails. My machine is quite fast, is that normal?

I've seen `test-mmap` timeout within 60 seconds, but not lately.  Older baselines of `quic/musl` were more likely to encounter this.  I'd presumed that newer optimizations made by @taylorsimpson  remove the need to extend the timeout.

So, to answer your question -- no, it's not normal on `master` anymore.  But it is ultimately could depend on unstable things like the performance of the CPU and concurrent load.  As you say, your machine is fast, so we should try to explain this some other way.

**Comment by androm3da** [comment]
> > I bumped the repos and now everything seems to work, except for the fact that I have to increase the timeout for tests to pass to 60 seconds, otherwise `test-mmap` fails. My machine is quite fast, is that normal?
> 
> I've seen `test-mmap` timeout within 60 seconds, but not lately. Older baselines of `quic/musl` were more likely to encounter this. I'd presumed that newer optimizations made by @taylorsimpson remove the need to extend the timeout.
> 
> So, to answer your question -- no, it's not normal on `master` anymore. But it is ultimately could depend on unstable things like the performance of the CPU and concurrent load. As you say, your machine is fast, so we should try to explain this some other way.

@taylorsimpson says that he has a change that alters the timeout for this test.

One option we've discussed to address this is to consider changing the test design to access a byte count that is independent of the page size.

**Comment by aleclearmind** [comment]
@androm3da I've pushed my commits with `Signed-Off-By`. From now on, we'll have it for all of our commits.
Feel free to handle this as you prefer.

**Pull request merged**
