### PR TITLE
Fix some occurrences of -Wshadow=local

### PR DESCRIPTION
**Pull request by androm3da**

### CODE REVIEW

**Comment by androm3da** [comment]
This is for https://www.mail-archive.com/qemu-devel@nongnu.org/msg991974.html

These changes are incomplete but these were the "easy" ones.

Bad thing about the changes so far is that it's inconsistent whether we use the locally-scoped loop indices or not.

I based this on @quic-mathbern 's change because I think it will have some interaction, especially if we decide to convert any macros to functions.

**Review by quic-mathbern — APPROVED** [review]
Nice, LGTM!

Only at `HELPER(commit_hvx_stores)()`, I'm not sure if those changes are needed for `-Wshadow`... `int i` doesn't seem to be shadowed?

**Comment by androm3da** [comment]
> Nice, LGTM!
> 
> Only at `HELPER(commit_hvx_stores)()`, I'm not sure if those changes are needed for `-Wshadow`... `int i` doesn't seem to be shadowed?

It's used by macros like `SCATTER_OP_WRITE_TO_MEM()`.

e.g.
```
In file included from ../target/hexagon/op_helper.c:31:
../target/hexagon/mmvec/macros.h:205:18: error: declaration of ‘i’ shadows a previous local [-Werror=shadow=compatible-local]
  205 |         for (int i = 0; i < sizeof(MMVector); i += sizeof(TYPE)) { \
      |                  ^
../target/hexagon/op_helper.c:157:17: note: in expansion of macro ‘SCATTER_OP_WRITE_TO_MEM’
  157 |                 SCATTER_OP_WRITE_TO_MEM(uint16_t);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
../target/hexagon/op_helper.c:135:9: note: shadowed declaration is here
  135 |     int i;
      |         ^
In file included from ../target/hexagon/op_helper.c:31:
../target/hexagon/mmvec/macros.h:204:19: error: declaration of ‘ra’ shadows a previous local [-Werror=shadow=compatible-local]
  204 |         uintptr_t ra = GETPC(); \
      |                   ^~
../target/hexagon/op_helper.c:160:17: note: in expansion of macro ‘SCATTER_OP_WRITE_TO_MEM’
  160 |                 SCATTER_OP_WRITE_TO_MEM(uint32_t);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
../target/hexagon/op_helper.c:134:15: note: shadowed declaration is here
  134 |     uintptr_t ra = GETPC();
      |               ^~

```

**Comment by quic-mathbern** [comment]
> > Only at `HELPER(commit_hvx_stores)()`, I'm not sure if those changes are needed for `-Wshadow`... `int i` doesn't seem to be shadowed?
> 
> It's used by macros like `SCATTER_OP_WRITE_TO_MEM()`.

Oh, ok, I see. If you're sending upstream, might be worth mentioning that case and example in the commit message, I think. To motivate the change.

**Comment by androm3da** [comment]
This was merged upstream.

**Pull request closed without merging**
